### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by beliaev-maksim**
Links were pointing to the wrong lib

### CODE REVIEW

**Review by sed-i — APPROVED** [review]
Bump LIBPATCH?

**Comment by beliaev-maksim** [comment]
> Bump LIBPATCH?

for both libs?

**Comment by sed-i** [comment]
> > Bump LIBPATCH?
> 
> for both libs?

Yep. Check on charmhub we're `N+1`-ing it.
https://charmhub.io/prometheus-k8s/libraries/

Or try the latest [`jhack charm vinfo`](https://discourse.charmhub.io/t/introducing-jhack-charm-vinfo/7593) :)

**Comment by beliaev-maksim** [comment]
@sed-i done

**Pull request merged**
